version: '3'

services:
  db:
    container_name: "db-prisma"
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=mydb
      - MYSQL_ROOT_PASSWORD=password
    ports:
      - '3306:3306'
    networks:
      - prisma-app

networks:
  prisma-app:
    driver: bridge
